Social validation
bakaphp/canvas-core pull request #522
Opened 2020-10-16 19:08 UTC by FredPeal

social validation on 0.2

2020-10-16 19:20 UTC, kaioken requested changes

2020-10-16 19:20 UTC, kaioken commented on src/Models/Sources.php
> +    public function validation(string $email, string $token) : bool
@FredPeal move this out of a model to a library

2020-10-16 19:20 UTC, kaioken commented
@FredPeal @rwhite27 we cant merge this until we talk with the frontend

2020-10-22 18:11 UTC, rwhite27 approved these changes

2020-12-28 20:04 UTC, closed without merging