Unsubscribe 0.2
bakaphp/canvas-core pull request #588
Opened 2021-01-18 19:13 UTC by dasdo

2021-01-18 19:38 UTC, rwhite27 approved these changes

2021-01-19 14:05 UTC, kaioken requested changes

2021-01-19 14:05 UTC, kaioken commented on routes/api.php
> +    Route::post('/users/{id}/unsubscribe')->controller('UsersController')->action('unsubscribe'),
@dasdo @SparoHawk if im unsubscribing shouldnt it be a delete?

2021-01-19 14:05 UTC, kaioken commented on src/Api/Controllers/UsersController.php
> +            $notificationType = NotificationType::findFirst($typeId);
@dasdo use findfirstorFail , no?

2021-01-19 14:05 UTC, kaioken commented on src/Api/Controllers/UsersController.php
> +            $unsubscribe[] = Notifications::unsubscribe($user, (int) $typeId, (int) $systemModulesId);
@dasdo its good for now ? but shouldnt this metho of unbuscribe be on the users end?

Im a user who is unsubscribing from the type X?

so it should be $user->unsubcribe(NotificationType)?

2021-01-19 14:05 UTC, kaioken commented on src/Models/Notifications.php
> +    public function isUnsubscribe(?Users $user) : bool
@dasdo I thinks this should be on the users end

2021-01-20 12:40 UTC, dasdo commented on routes/api.php
> +    Route::post('/users/{id}/unsubscribe')->controller('UsersController')->action('unsubscribe'),
Information is being added to the database, so it's post

2021-01-20 12:41 UTC, dasdo commented on src/Api/Controllers/UsersController.php
> +            $notificationType = NotificationType::findFirst($typeId);
No, we can receive -1 which is not a list.

2021-01-20 15:14 UTC, kaioken approved these changes

2021-01-20 15:20 UTC, merged

2021-01-20 15:21 UTC, rwhite27 approved these changes