add users forgot code
bakaphp/canvas-core pull request #678
Opened 2021-06-04 13:58 UTC by dasdo

Version: 0.3

Description:

add user_recover_code field to user table to handle password recovery codes.

Features: Looking for an easier way to change the password from a mobile application

2021-06-04 14:16 UTC, kaioken requested changes

2021-06-04 14:16 UTC, kaioken commented on src/Models/Users.php
> +        $this->user_recover_code = sprintf("%06d", mt_rand(1, 999999));
@dasdo use phalcon randome library

2021-06-04 16:19 UTC, dasdo commented on src/Models/Users.php
> +        $this->user_recover_code = sprintf("%06d", mt_rand(1, 999999));
done

2021-06-04 18:54 UTC, rwhite27 approved these changes

2021-06-07 00:56 UTC, kaioken approved these changes

2021-06-07 00:56 UTC, kaioken commented on storage/db/migrations/20210604193743_users_forgot_code.php
> +            'collation' => 'latin1_swedish_ci',
@dasdo change this encoding to ut8mb4

2021-06-07 00:56 UTC, merged