Social validation
bakaphp/canvas-core pull request #707
Opened 2021-07-12 16:28 UTC by FredPeal

Version: The version of the package where the fix has been made.

Description:

Add an overview of the changes that your pr introduces, be short,concise and if there are any new libraries, please list them.

Features: why this feature is needed. 

Bug: the root cause and the impact it had. 

Refactor: what things are expected to improve from the refactor.

2021-07-12 18:44 UTC, rwhite27 approved these changes

2021-07-12 18:46 UTC, kaioken requested changes

2021-07-12 18:46 UTC, kaioken commented on src/Models/Sources.php
> +    public function validation(string $email, string $token) : bool
@FredPeal take this out of the module and move it to a validation or service

2021-07-12 18:48 UTC, kaioken requested changes

2021-07-12 18:48 UTC, kaioken commented on src/Providers/SocialProvider.php
> +class SocialProvider implements ServiceProviderInterface
@FredPeal need to add this provider to the test di

2021-07-16 13:23 UTC, kaioken requested changes

2021-07-16 13:23 UTC, kaioken commented on src/Validations/Sources.php
> +                            throw new Exception('Invalid user on google validation, payload or email incorrect');
@FredPeal create a specific exeception and its not define

2021-07-16 13:23 UTC, kaioken commented on src/Api/Controllers/AuthController.php
> +        } elseif($source->use_validation) {
@FredPeal encapsulate this on a method

2021-07-16 14:32 UTC, kaioken requested changes

2021-07-16 14:32 UTC, kaioken commented on src/Providers/SocialProvider.php
> +            function (bool $prefix = true) use ($app) {
@FredPeal what do you use prefix for?

2021-07-16 14:32 UTC, kaioken commented on src/Validations/Sources.php
> +                        if ($user) {
@FredPeal your are not validating the email here ?

2021-07-16 14:35 UTC, kaioken requested changes

2021-07-16 14:35 UTC, kaioken commented on src/Models/Sources.php
> +    public function hasValidation(): bool
@FredPeal woulnt it be use validatoin?

2021-07-19 13:14 UTC, rwhite27 approved these changes

2021-07-20 21:26 UTC, kaioken requested changes

2021-07-20 21:26 UTC, kaioken commented on src/AuthSocial/Facebook.php
> +class Google implements SocialInterface
@FredPeal how does it work?

2021-07-20 21:26 UTC, kaioken commented on src/Contracts/Auth/SocialInterface.php
> +interface SocialInterface {
@FredPeal social provider interface

2021-07-20 21:26 UTC, kaioken commented on src/AuthSocial/Facebook.php
> +namespace Canvas\AuthSocial;
@FredPeal Auth\Social\Providers

2021-11-23 14:47 UTC, closed without merging