message agrupation
bakaphp/canvas-core pull request #761
Opened 2021-11-02 08:42 UTC by jjsimonAB

Description:

Modifying the message so we can have proper groups

2021-11-02 13:14 UTC, kaioken requested changes

2021-11-02 13:14 UTC, kaioken commented on src/Notifications/Notification.php
> +        $newMessage = $oldMessage[0] . ' and other ' . $usersCount . 'users ' . $oldMessage[1];
@jjsimonAB dont you have to verify that this actually exist?

2021-11-02 23:20 UTC, kaioken requested changes

2021-11-02 23:20 UTC, kaioken commented on src/Notifications/Notification.php
> +        $group = json_decode($this->currentNotification->group);
@jjsimonAB validate its a json

2021-11-02 23:22 UTC, jjsimonAB commented on src/Notifications/Notification.php
> +        $group = json_decode($this->currentNotification->group);
Will do

2021-11-04 15:03 UTC, kaioken requested changes

2021-11-04 15:03 UTC, kaioken commented on src/Notifications/Notification.php
> +    protected function canAddNewUser($notificationGroup) : bool
@jjsimonAB  specify array params so you know you can count

2021-11-04 19:27 UTC, kaioken approved these changes

2021-11-04 19:37 UTC, arfenis approved these changes

2021-11-04 19:38 UTC, merged