Hotfix group notification
bakaphp/canvas-core pull request #766
Opened 2021-11-10 13:34 UTC by jjsimonAB

Version: 0.3

Bug: fixed group content group and group order

2021-11-10 13:42 UTC, kaioken requested changes

2021-11-10 13:42 UTC, kaioken commented on src/Notifications/Notification.php
> +            $mainUser = Users::findFirstById($this->currentNotification->from_users_id);
you can use just findFirst , no need byId

2021-11-10 13:42 UTC, kaioken commented on src/Notifications/Notification.php
> +            if ($user->email == $this->fromUser->email) {
@jjsimonAB why email not id?

2021-11-10 13:42 UTC, kaioken commented on tests/config.php
> +    'paths' => [
@jjsimonAB if this needed?

2021-11-11 14:16 UTC, arfenis approved these changes

2021-11-11 20:48 UTC, merged