feat: add notification channels migration,seeder,model
bakaphp/canvas-core pull request #831
Opened 2022-09-13 19:13 UTC by rwhite27

Features:

- Add notification_channels migration, seeder and model.
- Add relationship of notification channels to notification type model and table.

2022-09-13 20:06 UTC, kaioken requested changes

2022-09-13 20:06 UTC, kaioken commented on src/Models/NotificationChannels.php
> +    public string $name;
@rwhite27 add slug property and after create generate slug

2022-09-13 21:50 UTC, kaioken requested changes

2022-09-13 21:50 UTC, kaioken commented on src/Models/NotificationChannels.php
> +        $this->slug = strtolower(trim($this->name));
@rwhite27 use the slug genertor

``` 
use Phalcon\Utils\Slug;

 Slug::generate($name);
```

2022-09-14 13:39 UTC, rwhite27 commented on src/Models/NotificationChannels.php
> +        $this->slug = strtolower(trim($this->name));
ok

2022-09-14 13:42 UTC, kaioken approved these changes

2022-09-14 14:29 UTC, merged